[project]
name = "src"
version = "0.0.1"
description = "MLOps project"
authors = [{name = "Jaideep", email = "jaideep156@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}